version: '3.4'
services:
  db:
    image: postgres
    environment:
      - POSTGRES_USER=mresponse
      - POSTGRES_PASSWORD=mresponse
      - POSTGRES_DB=mresponse
    volumes:
      - pgdata:/var/lib/postgresql/data
  web:
    stdin_open: true
    tty: true
    build:
      context: .
      target: base
    image: mresponse-base
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=postgres://mresponse:mresponse@db:5432/mresponse
      - DJANGO_SETTINGS_MODULE=mresponse.settings.dev
    command: python manage.py runserver 0.0.0.0:8000
  frontend:
    build:
      context: .
      target: base-dev
    image: mresponse-base-dev
    ports:
      - "3000:3000"
    volumes:
      - ./mresponse/frontend/app:/app/frontend
    environment:
      - PORT=3000
    command: yarn start
volumes:
  pgdata:
    driver: local
