# Generated by Django 2.1.2 on 2018-10-12 13:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('responses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='submitted_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
