# Generated by Django 2.1.2 on 2018-10-17 16:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('responses', '0004_auto_20181015_1308'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResponseAssignedToUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moderation_assignments', to='responses.Response')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='response_assignment', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='responseassignedtouser',
            unique_together={('user', 'response')},
        ),
    ]
