# Generated by Django 2.1.2 on 2018-10-24 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('responses', '0004_auto_20181015_1308'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='submitted_to_play_store',
            field=models.BooleanField(default=False),
        ),
    ]
