# Generated by Django 2.1.2 on 2018-10-19 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('responses', '0004_auto_20181015_1308'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='play_store_reply_id',
            field=models.CharField(default='', max_length=255, blank=True),
        ),
    ]
