# Generated by Django 2.1.11 on 2019-11-01 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("responses", "0008_auto_20190429_1204"),
    ]

    operations = [
        migrations.AddField(
            model_name="response",
            name="rejected",
            field=models.BooleanField(default=False),
        ),
    ]
