# Generated by Django 2.1.11 on 2020-07-27 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("responses", "0009_response_rejected"),
    ]

    operations = [
        migrations.AddField(
            model_name="response",
            name="submitted_to_play_store_at",
            field=models.DateTimeField(editable=False, null=True),
        ),
    ]
