# Generated by Django 2.1.11 on 2020-06-17 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="is_archived",
            field=models.BooleanField(default=False),
        ),
    ]
