# Generated by Django 2.1.10 on 2019-08-26 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("canned_response", "0001_initial")]

    operations = [
        migrations.AlterField(
            model_name="response", name="text", field=models.TextField(max_length=360)
        )
    ]
