# Generated by Django 2.1.2 on 2019-04-24 10:10

from django.db import migrations

from ..constants import (
    FIRST_LEVEL_TRUSTED_CONTRIBUTOR, SECOND_LEVEL_TRUSTED_CONTRIBUTOR
)


def add_groups(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Group.objects.bulk_create([
        Group(name=FIRST_LEVEL_TRUSTED_CONTRIBUTOR),
        Group(name=SECOND_LEVEL_TRUSTED_CONTRIBUTOR)
    ])


def remove_groups(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Group.objects.filter(name=FIRST_LEVEL_TRUSTED_CONTRIBUTOR).delete()
    Group.objects.filter(name=SECOND_LEVEL_TRUSTED_CONTRIBUTOR).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_userprofile_avatar'),
    ]

    operations = [
        migrations.RunPython(add_groups, remove_groups),
    ]
