# Generated by Django 2.1.11 on 2020-07-15 09:44

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_userprofile_avatar_nullable"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="permissions_in_locales",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=3),
                blank=True,
                default=list,
                help_text="Languages in which this user should have their permissions. Takes a comma seperated list. Currently only affects the <em>can_bypass_staff_moderation</em> permission.",
                size=None,
            ),
        ),
    ]
