# Generated by Django 2.1.2 on 2018-10-12 13:51

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('responses', '0002_auto_20181012_1447'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Moderation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('positive_in_tone', models.BooleanField(verbose_name='is the response positive in tone?')),
                ('addressing_the_issue', models.BooleanField(verbose_name='is the response addressing the issue?')),
                ('personal', models.BooleanField(verbose_name='is the response personal?')),
                ('karma_points', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)])),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('moderator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='responses.Response')),
            ],
        ),
    ]
