# Generated by Django 2.1.2 on 2019-05-30 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moderations', '0003_auto_20181016_1533'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moderation',
            name='karma_points',
        ),
    ]
