# Generated by Django 2.1.2 on 2019-06-04 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("moderations", "0004_moderation_feedback_message"),
        ("moderations", "0005_approval"),
    ]

    operations = []
