# Generated by Django 2.1.2 on 2018-10-08 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('play_store_review_id', models.CharField(max_length=255, unique=True)),
                ('android_sdk_version', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('author_name', models.CharField(max_length=255)),
                ('review_text', models.TextField()),
                ('review_rating', models.SmallIntegerField(choices=[(1, '1 star'), (2, '2 stars'), (3, '3 stars'), (4, '4 stars'), (5, '5 stars')])),
                ('last_modified', models.DateTimeField()),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='applications.Application')),
                ('application_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='applications.ApplicationVersion')),
            ],
        ),
    ]
