# Generated by Django 2.1.2 on 2018-10-19 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20181012_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='review_language',
            field=models.CharField(default='', max_length=5),
            preserve_default=False,
        ),
    ]
