# Generated by Django 2.1.11 on 2020-08-03 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0004_bigger_review_language"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="review",
            options={"ordering": ["-created_on"]},
        ),
        migrations.AddField(
            model_name="review",
            name="created_on",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="review",
            name="updated_on",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
