# Generated by Django 2.1.11 on 2020-08-05 10:00

from django.db import migrations
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0005_auto_20200803_1345"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="review",
            options={
                "ordering": [
                    django.db.models.expressions.OrderBy(
                        django.db.models.expressions.F("created_on"),
                        descending=True,
                        nulls_last=True,
                    )
                ]
            },
        ),
    ]
