export const WELCOME_URL = '/'
export const LOGIN_URL = '/account/login'
export const SIGNUP_URL = '/account/signup'
export const FORGOT_PASSWORD_URL = '/account/forgot'
export const LOGOUT_URL = '/logout'
export const CALLBACK_URL = '/callback'
export const DASHBOARD_URL = '/dashboard'
